### ISSUE TITLE
Wakeup packet being sent mid stream with --retropie parameter

### ISSUE THREAD

**Issue by abwezi** [Fredrum/chiaki#16]
So now that all controller issues are ironed out I am attempting a long play session and have encountered what I believe to be my final issue and a very minor one. It appears the process for automatically connecting and/or sending wakeup packets may be looping at some point? After what seems like 20-30 minutes or so of gameplay my stream will be interrupted by the gui stating a wakeup packet was sent despite that I'm currently already streaming. The inconvenience is small, all I have to do is press the exit hotkey on my controller and then reboot chiaki and I'm good for another so many minutes, still just thought it should be reported though. Thanks again!

**Comment by Fredrum** [comment]
Hm I just kept my PS4 session on for about 1h and it didn't happen.
Have you got any more info? Do you run the PS5 or RPi on wifi?
Are you able to capture any of the shell output?
