### ISSUE TITLE
Sudden exits

### ISSUE THREAD

**Issue by Korijn** [Fredrum/chiaki#21]
I'm playing on raspberry pi 4b, remoting to a PS4 Pro. I've set resolution to 720p and everything is on the wired network. Sometimes, chiaki just randomly exits in the middle of a session, and even with verbose logging I can't see anything out of the ordinary.

It seems to have started happening once the PS5 remote play support launched, but I could be wrong on that...

Any ideas?

(I am running a debug build though)

**Comment by Fredrum** [comment]
Not sure. Could you please post the output of the terminal shell from after a crash?

Btw, with a PS4 Pro you should be able to do 1080p60.

**Comment by Korijn** [comment]
Yeah I reduced it to see if that would alleviate the problems, but nope. I'll write the log to a file next time I get around to it.

Thanks for the response & awesome work!

**Comment by Fredrum** [comment]
Closing for now.
If this is still an issue and you have more information for me to be able to assess feel free to re-open.
