### ISSUE TITLE
Cannot build with Retropie

### ISSUE THREAD

**Issue by ndoulgeridis** [Fredrum/chiaki#28]
I am trying to build it on Raspberry Pi4, Retropie distribution. I am trying the rpi02 branch and when I build I take this:

```

[ 10%] Built target chiaki-pb
[ 11%] Built target protobuf-nanopb-static
[ 23%] Built target gf_complete
[ 30%] Built target setsu
[ 34%] Built target jerasure
[ 82%] Built target chiaki-lib
[ 84%] Building CXX object rpi/CMakeFiles/chiaki-rpi.dir/src/gui.cpp.o
/tmp/chiaki-rpi/rpi/src/gui.cpp: In member function ‘bool ImguiSdlWindow::UpdateAVFrame()’:
/tmp/chiaki-rpi/rpi/src/gui.cpp:890:10: error: ‘av_frame_cropped_width’ was not declared in this scope
   *a++ = av_frame_cropped_width(frame);
          ^~~~~~~~~~~~~~~~~~~~~~
/tmp/chiaki-rpi/rpi/src/gui.cpp:890:10: note: suggested alternative: ‘av_frame_copy_props’
   *a++ = av_frame_cropped_width(frame);
          ^~~~~~~~~~~~~~~~~~~~~~
          av_frame_copy_props
/tmp/chiaki-rpi/rpi/src/gui.cpp:892:10: error: ‘av_frame_cropped_height’ was not declared in this scope
   *a++ = av_frame_cropped_height(frame);
          ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/chiaki-rpi/rpi/src/gui.cpp:892:10: note: suggested alternative: ‘av_frame_copy_props’
   *a++ = av_frame_cropped_height(frame);
          ^~~~~~~~~~~~~~~~~~~~~~~
          av_frame_copy_props
make[2]: *** [rpi/CMakeFiles/chiaki-rpi.dir/build.make:128: rpi/CMakeFiles/chiaki-rpi.dir/src/gui.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:396: rpi/CMakeFiles/chiaki-rpi.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

Do you have a clue what I miss? I am trying o build it from SSH on a retropie distribution which is up to date.

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by Fredrum** [comment]
Hi yes this is because you are using the Buster version of the RPi OS.
It does not have the required version of avcodec and related libraries.  They habve custom Raspberry code in them which is in the Bullseye release.

You can build that avcodec yourself from source but I don't have a set of clear instructions for that yet.

In those cases Ive used the `test/4.3.2/rpi_main` branch of the repo  https://github.com/jc-kynesim/rpi-ffmpeg.git

Mitu from Retropie has mentioned that they are working on a Bullseye version but they don't know how long it would take.

**Comment by Fredrum** [comment]
I do have some jotted down notes here about how to build,

https://github.com/Fredrum/hwdectogl/blob/1d4a9271c2f37620d4fb6a53f3576f1064edbb0c/notes.txt#L24

CRUCIAL is to start by doing,

```
export CPPFLAGS="-I/usr/include/libdrm"
./configure
```
AFTER having installed all the dependencies
NOTE you don't want to do this line  `sudo apt install libsdl2-dev`  as that would give you a too old version of SDL.

I think it builds static libs (.a)  by default so you might want to figure our how to change to Shared.

**Comment by Fredrum** [comment]
I now have an build+install script for the custom ffmpeg/avcodec that's needed for Chiaki on Raspberry Pi.
If you want to you could try running this before building Chiaki,
https://github.com/Fredrum/chiaki/blob/rpi02/install_ffmpeg.sh

It has been tested on Ubuntu 22.04 and Debian Bullseye (both raspberrry).

**Comment by Fredrum** [comment]
And I now have a rough guide for retropie 4.8.
You'll need to cross check the main instruction with these Retropie specific differences,

https://github.com/Fredrum/chiaki/wiki/More-rpi02-Instructions-and-tips#retropie

**Comment by Fredrum** [comment]
Closing issue.
You can start a new issue if there's any problems.
