### ISSUE TITLE
Bullseye 32-bit and 64-bit

### ISSUE THREAD

**Issue by hybotix** [Fredrum/chiaki#31]
Chiaki does not support ARM 6-bit OS such as Raspberry Pi Bullseye.

Is this on the radar for development?

**Comment by Fredrum** [comment]
Yes my 'rpi02' branch should work with 64bit Raspberry OS Bullseye. See,
https://youtu.be/qDthHmD30us?t=39

https://github.com/Fredrum/chiaki/wiki/rpi02---branch-for-Bullseye,-64bit,-h265-and-kmsdrm

**Comment by Fredrum** [comment]
Closing this. Feel free to start a new issue if you're having trouble getting 64bit bullseye to work.

**Comment by hybotix** [comment]
Why was this closed? Your software will still not build on Bullseye. It does not find SDL even though it has been installed using your sript.

**Comment by Fredrum** [comment]
If you want some help you'll have to provide some information on what exactly your doing and what error messages you're having. 

Rpi Hardware.
OS distribution.

**Comment by hybotix** [comment]
It can not FIND SDL. I have installed SDL by running the script in the
repository.
